image: python:3.9

test:
  stage: test
  script:
    - python3 -m pip install --user pipx
    - python3 -m pipx ensurepath
    - python3 -m pipx install poetry
    - source ~/.bashrc
    - poetry install
    - poetry run make -C docs/ html
    - cp -r docs/build/html public
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  script:
    - python3 -m pip install --user pipx
    - python3 -m pipx ensurepath
    - python3 -m pipx install poetry
    - source ~/.bashrc
    - poetry install
    - poetry run make -C docs/ html
    - cp -r docs/build/html public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
