image: python:3.9

test:
  stage: test
  script:
    - pip install pipx
    - pipx ensurepath
    - source ~/.bashrc
    - pipx install poetry
    - poetry install
    - poetry run make -C docs/ html
    - cp -r docs/build/html public
  artifacts:
    paths:
      - public
  environment:
    name: Preview
    url: "https://$CI_PROJECT_NAMESPACE.gitlab.io/-/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/public/index.html"
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  script:
    - pip install pipx
    - pipx ensurepath
    - source ~/.bashrc
    - pipx install poetry
    - poetry install
    - poetry run make -C docs/ html
    - cp -r docs/build/html public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
