image: python:3.9-alpine

test:
  stage: test
  script:
    - pip3 install pipx 
    - pipx install poetry
    - poetry install
    - poetry run make -C docs/ html
    - cp -r docs/build/html public
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  script:
    - pip3 install pipx 
    - pipx install poetry
    - poetry install
    - poetry run make -C docs/ html
    - cp -r docs/build/html public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
