on:
  push:
    branches:
      - main
  workflow_dispatch:

name: deploy-internal
run-name: Deploy docs internally
jobs:
  build-docs:
    uses: ./.github/workflows/build-docs.yml

  deploy-internal:
    runs-on: ubuntu-latest
    needs: build-docs
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download docs artifact
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: docs/build

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/build
          branch: gh-pages
          clean-exclude: pr-preview
          force: false
