name: CI
on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build-docs:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.9

      - name: Install deps
        run: pdm install

      - name: Build docs
        run: pdm run build

      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/build

  publish-docs:
    needs: build-docs
    if: ${{ github.repository == 'chipflow/chipflow-docs' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download docs artifact
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: docs/

      - name: Publish "latest" docs
        if: ${{ github.event_name == 'push' && github.event.ref == 'refs/heads/main' }}
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          repository-name: chipflow/chipflow.github.io
          ssh-key: ${{ secrets.PAGES_DEPLOY_KEY }}
          branch: main
          folder: docs/
          target-folder: en/latest/
