name: Release docs LIVE!
on:
  release:

jobs:
  build-docs:
    uses: ./.github/workflows/build-docs.yml

  publish-docs:
    needs: build-docs
    if: ${{ github.repository == 'chipflow/chipflow-docs' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download docs artifact
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: docs/build

      - name: Publish "latest" docs
        if: ${{ github.event_name == 'push' && github.event.ref == 'refs/heads/main' }}
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          repository-name: chipflow/chipflow.github.io
          ssh-key: ${{ secrets.PAGES_DEPLOY_KEY }}
          branch: main
          folder: docs/build
          target-folder: en/latest/
